### use ballance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}

### cancel ballance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "2e172a80a2e049b3b8b5c0b9b99136bb",
  "accountNumber": "1000000002",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/121f57ae0e904d04b98eb039ab063307