### use ballance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use ballance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel ballance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "783c1a81de7b475d866c5c39db9fd98a",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/121f57ae0e904d04b98eb039ab063307